name: PROXY Updater

on:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        curl https://xlr74.herokuapp.com/bomb/9891110582
        curl https://xlr71.herokuapp.com/bomb/9868796414
        echo compleated 
        df -h
        free -h
        
